import Loader from '@/components/Loader';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Suspense } from 'react';
import { MantineProvider } from '@mantine/core';
import ApolloWrapper from '@/components/ApolloWrapper';
import '@mantine/core/styles.css';
import { StoreRoot } from '@/components/StoreRoot';
import Link from 'next/link';
import { FeatureRoot } from '@/feature/FeatureRoot';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section>
          <Link href="/">
            <h1>NextJs POC</h1>
          </Link>
        </section>
        <hr />
        <ApolloWrapper>
          <FeatureRoot>
            <StoreRoot>
              <MantineProvider>{children}</MantineProvider>
            </StoreRoot>
          </FeatureRoot>
        </ApolloWrapper>
        <hr />
        <section>--- Footer ---</section>
      </body>
    </html>
  );
}
